// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package sakuracloud

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// Get information about an existing Bucket Object.
func LookupBucketObject(ctx *pulumi.Context, args *LookupBucketObjectArgs, opts ...pulumi.InvokeOption) (*LookupBucketObjectResult, error) {
	var rv LookupBucketObjectResult
	err := ctx.Invoke("sakuracloud:index/getBucketObject:getBucketObject", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBucketObject.
type LookupBucketObjectArgs struct {
	// The access key for using SakuraCloud Object Storage API.
	AccessKey string `pulumi:"accessKey"`
	// The name of bucket.
	Bucket string `pulumi:"bucket"`
	// The name of the BucketObject.
	Key string `pulumi:"key"`
	// The secret key for using SakuraCloud Object Storage API.
	SecretKey string `pulumi:"secretKey"`
}

// A collection of values returned by getBucketObject.
type LookupBucketObjectResult struct {
	AccessKey string `pulumi:"accessKey"`
	// The body of the BucketObject.
	Body   string `pulumi:"body"`
	Bucket string `pulumi:"bucket"`
	// The content type of the BucketObject.
	ContentType string `pulumi:"contentType"`
	// The etag of the BucketObject.
	Etag string `pulumi:"etag"`
	// The URL for cached access to the BucketObject via HTTP.
	HttpCacheUrl string `pulumi:"httpCacheUrl"`
	// The URL with path-format for accessing the BucketObject via HTTP.
	HttpPathUrl string `pulumi:"httpPathUrl"`
	// The URL for accessing the BucketObject via HTTP.
	HttpUrl string `pulumi:"httpUrl"`
	// The URL for cached access to the BucketObject via HTTPS.
	HttpsCacheUrl string `pulumi:"httpsCacheUrl"`
	// The URL with path-format for accessing the BucketObject via HTTPS.
	HttpsPathUrl string `pulumi:"httpsPathUrl"`
	// The URL for accessing the BucketObject via HTTPS.
	HttpsUrl string `pulumi:"httpsUrl"`
	// The provider-assigned unique ID for this managed resource.
	Id  string `pulumi:"id"`
	Key string `pulumi:"key"`
	// The time when the BucketObject last modified.
	LastModified string `pulumi:"lastModified"`
	SecretKey    string `pulumi:"secretKey"`
	// The size of the BucketObject in bytes.
	Size int `pulumi:"size"`
}
