// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package sakuracloud

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Use this data source to retrieve information about a SakuraCloud Icon.
//
// > This content is derived from https://github.com/sacloud/terraform-provider-sakuracloud/blob/master/website/docs/d/icon.html.markdown.
func LookupIcon(ctx *pulumi.Context, args *GetIconArgs) (*GetIconResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["filters"] = args.Filters
		inputs["nameSelectors"] = args.NameSelectors
		inputs["tagSelectors"] = args.TagSelectors
	}
	outputs, err := ctx.Invoke("sakuracloud:index/getIcon:getIcon", inputs)
	if err != nil {
		return nil, err
	}
	return &GetIconResult{
		Body: outputs["body"],
		Filters: outputs["filters"],
		Name: outputs["name"],
		NameSelectors: outputs["nameSelectors"],
		TagSelectors: outputs["tagSelectors"],
		Tags: outputs["tags"],
		Url: outputs["url"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getIcon.
type GetIconArgs struct {
	// The map of filter key and value.
	Filters interface{}
	// The list of names to filtering.
	NameSelectors interface{}
	// The list of tags to filtering.
	TagSelectors interface{}
}

// A collection of values returned by getIcon.
type GetIconResult struct {
	// Base64 encoded icon data (size:`small`).
	Body interface{}
	Filters interface{}
	// The name of the resource.
	Name interface{}
	NameSelectors interface{}
	TagSelectors interface{}
	// The tag list of the resources.
	Tags interface{}
	// URL to access this resource.
	Url interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
