// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package sakuracloud

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides a SakuraCloud Mobile Gateway Static Route resource. This can be used to create, update, and delete Mobile Gateway Static Routes.
// 
// ## Import (not supported)
// 
// Import of Mobile Gateway Static Route is not supported.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-sakuracloud/blob/master/website/docs/r/mobile_gateway_static_route.html.markdown.
type MobileGatewayStaticRoute struct {
	s *pulumi.ResourceState
}

// NewMobileGatewayStaticRoute registers a new resource with the given unique name, arguments, and options.
func NewMobileGatewayStaticRoute(ctx *pulumi.Context,
	name string, args *MobileGatewayStaticRouteArgs, opts ...pulumi.ResourceOpt) (*MobileGatewayStaticRoute, error) {
	if args == nil || args.MobileGatewayId == nil {
		return nil, errors.New("missing required argument 'MobileGatewayId'")
	}
	if args == nil || args.NextHop == nil {
		return nil, errors.New("missing required argument 'NextHop'")
	}
	if args == nil || args.Prefix == nil {
		return nil, errors.New("missing required argument 'Prefix'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["mobileGatewayId"] = nil
		inputs["nextHop"] = nil
		inputs["prefix"] = nil
		inputs["zone"] = nil
	} else {
		inputs["mobileGatewayId"] = args.MobileGatewayId
		inputs["nextHop"] = args.NextHop
		inputs["prefix"] = args.Prefix
		inputs["zone"] = args.Zone
	}
	s, err := ctx.RegisterResource("sakuracloud:index/mobileGatewayStaticRoute:MobileGatewayStaticRoute", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &MobileGatewayStaticRoute{s: s}, nil
}

// GetMobileGatewayStaticRoute gets an existing MobileGatewayStaticRoute resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMobileGatewayStaticRoute(ctx *pulumi.Context,
	name string, id pulumi.ID, state *MobileGatewayStaticRouteState, opts ...pulumi.ResourceOpt) (*MobileGatewayStaticRoute, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["mobileGatewayId"] = state.MobileGatewayId
		inputs["nextHop"] = state.NextHop
		inputs["prefix"] = state.Prefix
		inputs["zone"] = state.Zone
	}
	s, err := ctx.ReadResource("sakuracloud:index/mobileGatewayStaticRoute:MobileGatewayStaticRoute", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &MobileGatewayStaticRoute{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *MobileGatewayStaticRoute) URN() *pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *MobileGatewayStaticRoute) ID() *pulumi.IDOutput {
	return r.s.ID()
}

// The ID of the Mobile Gateway to set Static Route.
func (r *MobileGatewayStaticRoute) MobileGatewayId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["mobileGatewayId"])
}

// The IP address of the next hop.
func (r *MobileGatewayStaticRoute) NextHop() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["nextHop"])
}

// The routing prefix (format:`CIDR`).
func (r *MobileGatewayStaticRoute) Prefix() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["prefix"])
}

// The ID of the zone to which the resource belongs.
func (r *MobileGatewayStaticRoute) Zone() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["zone"])
}

// Input properties used for looking up and filtering MobileGatewayStaticRoute resources.
type MobileGatewayStaticRouteState struct {
	// The ID of the Mobile Gateway to set Static Route.
	MobileGatewayId interface{}
	// The IP address of the next hop.
	NextHop interface{}
	// The routing prefix (format:`CIDR`).
	Prefix interface{}
	// The ID of the zone to which the resource belongs.
	Zone interface{}
}

// The set of arguments for constructing a MobileGatewayStaticRoute resource.
type MobileGatewayStaticRouteArgs struct {
	// The ID of the Mobile Gateway to set Static Route.
	MobileGatewayId interface{}
	// The IP address of the next hop.
	NextHop interface{}
	// The routing prefix (format:`CIDR`).
	Prefix interface{}
	// The ID of the zone to which the resource belongs.
	Zone interface{}
}
