// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sakuracloud
{
    /// <summary>
    /// Provides a SakuraCloud Auto Backup resource. This can be used to create, update, and delete Auto Backups.
    /// 
    /// &gt; This content is derived from https://github.com/sacloud/terraform-provider-sakuracloud/blob/master/website/docs/r/auto_backup.html.markdown.
    /// </summary>
    public partial class AutoBackup : Pulumi.CustomResource
    {
        /// <summary>
        /// The description of the resource.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The ID of the target disk. 
        /// </summary>
        [Output("diskId")]
        public Output<string> DiskId { get; private set; } = null!;

        /// <summary>
        /// The ID of the icon.
        /// </summary>
        [Output("iconId")]
        public Output<string?> IconId { get; private set; } = null!;

        /// <summary>
        /// Max number of backups to keep.
        /// </summary>
        [Output("maxBackupNum")]
        public Output<int?> MaxBackupNum { get; private set; } = null!;

        /// <summary>
        /// The name of the resource.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The tag list of the resources.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// Day of the week to get backup.  
        /// Valid values are the following: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
        /// </summary>
        [Output("weekdays")]
        public Output<ImmutableArray<string>> Weekdays { get; private set; } = null!;

        /// <summary>
        /// The ID of the zone to which the resource belongs.  
        /// Valid value is one of the following: ["is1b" / "tk1a" / "is1a"]
        /// </summary>
        [Output("zone")]
        public Output<string> Zone { get; private set; } = null!;


        /// <summary>
        /// Create a AutoBackup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AutoBackup(string name, AutoBackupArgs args, CustomResourceOptions? options = null)
            : base("sakuracloud:index/autoBackup:AutoBackup", name, args, MakeResourceOptions(options, ""))
        {
        }

        private AutoBackup(string name, Input<string> id, AutoBackupState? state = null, CustomResourceOptions? options = null)
            : base("sakuracloud:index/autoBackup:AutoBackup", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AutoBackup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AutoBackup Get(string name, Input<string> id, AutoBackupState? state = null, CustomResourceOptions? options = null)
        {
            return new AutoBackup(name, id, state, options);
        }
    }

    public sealed class AutoBackupArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the resource.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The ID of the target disk. 
        /// </summary>
        [Input("diskId", required: true)]
        public Input<string> DiskId { get; set; } = null!;

        /// <summary>
        /// The ID of the icon.
        /// </summary>
        [Input("iconId")]
        public Input<string>? IconId { get; set; }

        /// <summary>
        /// Max number of backups to keep.
        /// </summary>
        [Input("maxBackupNum")]
        public Input<int>? MaxBackupNum { get; set; }

        /// <summary>
        /// The name of the resource.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// The tag list of the resources.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("weekdays", required: true)]
        private InputList<string>? _weekdays;

        /// <summary>
        /// Day of the week to get backup.  
        /// Valid values are the following: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
        /// </summary>
        public InputList<string> Weekdays
        {
            get => _weekdays ?? (_weekdays = new InputList<string>());
            set => _weekdays = value;
        }

        /// <summary>
        /// The ID of the zone to which the resource belongs.  
        /// Valid value is one of the following: ["is1b" / "tk1a" / "is1a"]
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public AutoBackupArgs()
        {
        }
    }

    public sealed class AutoBackupState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the resource.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The ID of the target disk. 
        /// </summary>
        [Input("diskId")]
        public Input<string>? DiskId { get; set; }

        /// <summary>
        /// The ID of the icon.
        /// </summary>
        [Input("iconId")]
        public Input<string>? IconId { get; set; }

        /// <summary>
        /// Max number of backups to keep.
        /// </summary>
        [Input("maxBackupNum")]
        public Input<int>? MaxBackupNum { get; set; }

        /// <summary>
        /// The name of the resource.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// The tag list of the resources.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("weekdays")]
        private InputList<string>? _weekdays;

        /// <summary>
        /// Day of the week to get backup.  
        /// Valid values are the following: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
        /// </summary>
        public InputList<string> Weekdays
        {
            get => _weekdays ?? (_weekdays = new InputList<string>());
            set => _weekdays = value;
        }

        /// <summary>
        /// The ID of the zone to which the resource belongs.  
        /// Valid value is one of the following: ["is1b" / "tk1a" / "is1a"]
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public AutoBackupState()
        {
        }
    }
}
