// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sakuracloud
{
    /// <summary>
    /// Manages a SakuraCloud ESME resource.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Sakuracloud = Pulumi.Sakuracloud;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var foobar = new Sakuracloud.ESME("foobar", new Sakuracloud.ESMEArgs
    ///         {
    ///             Description = "description",
    ///             Tags = 
    ///             {
    ///                 "tag1",
    ///                 "tag2",
    ///             },
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// </summary>
    [SakuracloudResourceType("sakuracloud:index/eSME:ESME")]
    public partial class ESME : Pulumi.CustomResource
    {
        /// <summary>
        /// The description of the ESME. The length of this value must be in the range [`1`-`512`].
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The icon id to attach to the ESME.
        /// </summary>
        [Output("iconId")]
        public Output<string?> IconId { get; private set; } = null!;

        /// <summary>
        /// The name of the ESME. The length of this value must be in the range [`1`-`64`].
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The API URL for send SMS with generated OTP.
        /// </summary>
        [Output("sendMessageWithGeneratedOtpApiUrl")]
        public Output<string> SendMessageWithGeneratedOtpApiUrl { get; private set; } = null!;

        /// <summary>
        /// The API URL for send SMS with inputted OTP.
        /// </summary>
        [Output("sendMessageWithInputtedOtpApiUrl")]
        public Output<string> SendMessageWithInputtedOtpApiUrl { get; private set; } = null!;

        /// <summary>
        /// Any tags to assign to the ESME.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a ESME resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ESME(string name, ESMEArgs? args = null, CustomResourceOptions? options = null)
            : base("sakuracloud:index/eSME:ESME", name, args ?? new ESMEArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ESME(string name, Input<string> id, ESMEState? state = null, CustomResourceOptions? options = null)
            : base("sakuracloud:index/eSME:ESME", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ESME resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ESME Get(string name, Input<string> id, ESMEState? state = null, CustomResourceOptions? options = null)
        {
            return new ESME(name, id, state, options);
        }
    }

    public sealed class ESMEArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the ESME. The length of this value must be in the range [`1`-`512`].
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The icon id to attach to the ESME.
        /// </summary>
        [Input("iconId")]
        public Input<string>? IconId { get; set; }

        /// <summary>
        /// The name of the ESME. The length of this value must be in the range [`1`-`64`].
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Any tags to assign to the ESME.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public ESMEArgs()
        {
        }
    }

    public sealed class ESMEState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the ESME. The length of this value must be in the range [`1`-`512`].
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The icon id to attach to the ESME.
        /// </summary>
        [Input("iconId")]
        public Input<string>? IconId { get; set; }

        /// <summary>
        /// The name of the ESME. The length of this value must be in the range [`1`-`64`].
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The API URL for send SMS with generated OTP.
        /// </summary>
        [Input("sendMessageWithGeneratedOtpApiUrl")]
        public Input<string>? SendMessageWithGeneratedOtpApiUrl { get; set; }

        /// <summary>
        /// The API URL for send SMS with inputted OTP.
        /// </summary>
        [Input("sendMessageWithInputtedOtpApiUrl")]
        public Input<string>? SendMessageWithInputtedOtpApiUrl { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Any tags to assign to the ESME.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public ESMEState()
        {
        }
    }
}
