// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sakuracloud
{
    public static class GetSwitch
    {
        /// <summary>
        /// Get information about an existing Switch.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Sakuracloud = Pulumi.Sakuracloud;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var foobar = Output.Create(Sakuracloud.GetSwitch.InvokeAsync(new Sakuracloud.GetSwitchArgs
        ///         {
        ///             Filter = new Sakuracloud.Inputs.GetSwitchFilterArgs
        ///             {
        ///                 Names = 
        ///                 {
        ///                     "foobar",
        ///                 },
        ///             },
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetSwitchResult> InvokeAsync(GetSwitchArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetSwitchResult>("sakuracloud:index/getSwitch:getSwitch", args ?? new GetSwitchArgs(), options.WithVersion());
    }


    public sealed class GetSwitchArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// One or more values used for filtering, as defined below.
        /// </summary>
        [Input("filter")]
        public Inputs.GetSwitchFilterArgs? Filter { get; set; }

        /// <summary>
        /// The name of zone that the Switch is in (e.g. `is1a`, `tk1a`).
        /// </summary>
        [Input("zone")]
        public string? Zone { get; set; }

        public GetSwitchArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetSwitchResult
    {
        /// <summary>
        /// The bridge id attached to the Switch.
        /// </summary>
        public readonly string BridgeId;
        /// <summary>
        /// The description of the Switch.
        /// </summary>
        public readonly string Description;
        public readonly Outputs.GetSwitchFilterResult? Filter;
        /// <summary>
        /// The icon id attached to the Switch.
        /// </summary>
        public readonly string IconId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the Switch.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// A list of server id connected to the Switch.
        /// </summary>
        public readonly ImmutableArray<string> ServerIds;
        /// <summary>
        /// Any tags assigned to the Switch.
        /// </summary>
        public readonly ImmutableArray<string> Tags;
        public readonly string Zone;

        [OutputConstructor]
        private GetSwitchResult(
            string bridgeId,

            string description,

            Outputs.GetSwitchFilterResult? filter,

            string iconId,

            string id,

            string name,

            ImmutableArray<string> serverIds,

            ImmutableArray<string> tags,

            string zone)
        {
            BridgeId = bridgeId;
            Description = description;
            Filter = filter;
            IconId = iconId;
            Id = id;
            Name = name;
            ServerIds = serverIds;
            Tags = tags;
            Zone = zone;
        }
    }
}
