// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sakuracloud
{
    /// <summary>
    /// Provides a SakuraCloud Private Host resource. This can be used to create, update, and delete Private Hosts.
    /// 
    /// &gt; This content is derived from https://github.com/sacloud/terraform-provider-sakuracloud/blob/master/website/docs/r/private_host.html.markdown.
    /// </summary>
    public partial class PrivateHost : Pulumi.CustomResource
    {
        /// <summary>
        /// The number of cores assigned to the Server.
        /// </summary>
        [Output("assignedCore")]
        public Output<int> AssignedCore { get; private set; } = null!;

        /// <summary>
        /// The size of memory allocated to the Server (unit:`GB`).
        /// </summary>
        [Output("assignedMemory")]
        public Output<int> AssignedMemory { get; private set; } = null!;

        /// <summary>
        /// The description of the resource.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The wait time (seconds) to do graceful shutdown the server connected to the resource.
        /// </summary>
        [Output("gracefulShutdownTimeout")]
        public Output<int?> GracefulShutdownTimeout { get; private set; } = null!;

        /// <summary>
        /// The HostName of the resource.
        /// </summary>
        [Output("hostname")]
        public Output<string> Hostname { get; private set; } = null!;

        /// <summary>
        /// The ID of the icon.
        /// </summary>
        [Output("iconId")]
        public Output<string?> IconId { get; private set; } = null!;

        /// <summary>
        /// The name of the resource.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The tag list of the resources.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// The ID of the zone to which the resource belongs.  
        /// Valid value is one of the following: ["is1a" / "is1b" / "tk1a"]
        /// </summary>
        [Output("zone")]
        public Output<string> Zone { get; private set; } = null!;


        /// <summary>
        /// Create a PrivateHost resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PrivateHost(string name, PrivateHostArgs? args = null, CustomResourceOptions? options = null)
            : base("sakuracloud:index/privateHost:PrivateHost", name, args, MakeResourceOptions(options, ""))
        {
        }

        private PrivateHost(string name, Input<string> id, PrivateHostState? state = null, CustomResourceOptions? options = null)
            : base("sakuracloud:index/privateHost:PrivateHost", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PrivateHost resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PrivateHost Get(string name, Input<string> id, PrivateHostState? state = null, CustomResourceOptions? options = null)
        {
            return new PrivateHost(name, id, state, options);
        }
    }

    public sealed class PrivateHostArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the resource.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The wait time (seconds) to do graceful shutdown the server connected to the resource.
        /// </summary>
        [Input("gracefulShutdownTimeout")]
        public Input<int>? GracefulShutdownTimeout { get; set; }

        /// <summary>
        /// The ID of the icon.
        /// </summary>
        [Input("iconId")]
        public Input<string>? IconId { get; set; }

        /// <summary>
        /// The name of the resource.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// The tag list of the resources.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The ID of the zone to which the resource belongs.  
        /// Valid value is one of the following: ["is1a" / "is1b" / "tk1a"]
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public PrivateHostArgs()
        {
        }
    }

    public sealed class PrivateHostState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The number of cores assigned to the Server.
        /// </summary>
        [Input("assignedCore")]
        public Input<int>? AssignedCore { get; set; }

        /// <summary>
        /// The size of memory allocated to the Server (unit:`GB`).
        /// </summary>
        [Input("assignedMemory")]
        public Input<int>? AssignedMemory { get; set; }

        /// <summary>
        /// The description of the resource.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The wait time (seconds) to do graceful shutdown the server connected to the resource.
        /// </summary>
        [Input("gracefulShutdownTimeout")]
        public Input<int>? GracefulShutdownTimeout { get; set; }

        /// <summary>
        /// The HostName of the resource.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// The ID of the icon.
        /// </summary>
        [Input("iconId")]
        public Input<string>? IconId { get; set; }

        /// <summary>
        /// The name of the resource.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// The tag list of the resources.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The ID of the zone to which the resource belongs.  
        /// Valid value is one of the following: ["is1a" / "is1b" / "tk1a"]
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public PrivateHostState()
        {
        }
    }
}
