// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sakuracloud
{
    /// <summary>
    /// Manages a SakuraCloud sakuracloud_webaccel_certificate.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.IO;
    /// using Pulumi;
    /// using Sakuracloud = Pulumi.Sakuracloud;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var site = Output.Create(Sakuracloud.GetWebAccel.InvokeAsync(new Sakuracloud.GetWebAccelArgs
    ///         {
    ///             Name = "your-site-name",
    ///         }));
    ///         var foobar = new Sakuracloud.WebAccelCertificate("foobar", new Sakuracloud.WebAccelCertificateArgs
    ///         {
    ///             SiteId = site.Apply(site =&gt; site.Id),
    ///             CertificateChain = File.ReadAllText("path/to/your/certificate/chain"),
    ///             PrivateKey = File.ReadAllText("path/to/your/private/key"),
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// </summary>
    [SakuracloudResourceType("sakuracloud:index/webAccelCertificate:WebAccelCertificate")]
    public partial class WebAccelCertificate : Pulumi.CustomResource
    {
        /// <summary>
        /// .
        /// </summary>
        [Output("certificateChain")]
        public Output<string> CertificateChain { get; private set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Output("dnsNames")]
        public Output<ImmutableArray<string>> DnsNames { get; private set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Output("issuerCommonName")]
        public Output<string> IssuerCommonName { get; private set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Output("notAfter")]
        public Output<string> NotAfter { get; private set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Output("notBefore")]
        public Output<string> NotBefore { get; private set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Output("privateKey")]
        public Output<string> PrivateKey { get; private set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Output("serialNumber")]
        public Output<string> SerialNumber { get; private set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Output("sha256Fingerprint")]
        public Output<string> Sha256Fingerprint { get; private set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Output("siteId")]
        public Output<string> SiteId { get; private set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Output("subjectCommonName")]
        public Output<string> SubjectCommonName { get; private set; } = null!;


        /// <summary>
        /// Create a WebAccelCertificate resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public WebAccelCertificate(string name, WebAccelCertificateArgs args, CustomResourceOptions? options = null)
            : base("sakuracloud:index/webAccelCertificate:WebAccelCertificate", name, args ?? new WebAccelCertificateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private WebAccelCertificate(string name, Input<string> id, WebAccelCertificateState? state = null, CustomResourceOptions? options = null)
            : base("sakuracloud:index/webAccelCertificate:WebAccelCertificate", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing WebAccelCertificate resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static WebAccelCertificate Get(string name, Input<string> id, WebAccelCertificateState? state = null, CustomResourceOptions? options = null)
        {
            return new WebAccelCertificate(name, id, state, options);
        }
    }

    public sealed class WebAccelCertificateArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// .
        /// </summary>
        [Input("certificateChain", required: true)]
        public Input<string> CertificateChain { get; set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Input("privateKey", required: true)]
        public Input<string> PrivateKey { get; set; } = null!;

        /// <summary>
        /// .
        /// </summary>
        [Input("siteId", required: true)]
        public Input<string> SiteId { get; set; } = null!;

        public WebAccelCertificateArgs()
        {
        }
    }

    public sealed class WebAccelCertificateState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// .
        /// </summary>
        [Input("certificateChain")]
        public Input<string>? CertificateChain { get; set; }

        [Input("dnsNames")]
        private InputList<string>? _dnsNames;

        /// <summary>
        /// .
        /// </summary>
        public InputList<string> DnsNames
        {
            get => _dnsNames ?? (_dnsNames = new InputList<string>());
            set => _dnsNames = value;
        }

        /// <summary>
        /// .
        /// </summary>
        [Input("issuerCommonName")]
        public Input<string>? IssuerCommonName { get; set; }

        /// <summary>
        /// .
        /// </summary>
        [Input("notAfter")]
        public Input<string>? NotAfter { get; set; }

        /// <summary>
        /// .
        /// </summary>
        [Input("notBefore")]
        public Input<string>? NotBefore { get; set; }

        /// <summary>
        /// .
        /// </summary>
        [Input("privateKey")]
        public Input<string>? PrivateKey { get; set; }

        /// <summary>
        /// .
        /// </summary>
        [Input("serialNumber")]
        public Input<string>? SerialNumber { get; set; }

        /// <summary>
        /// .
        /// </summary>
        [Input("sha256Fingerprint")]
        public Input<string>? Sha256Fingerprint { get; set; }

        /// <summary>
        /// .
        /// </summary>
        [Input("siteId")]
        public Input<string>? SiteId { get; set; }

        /// <summary>
        /// .
        /// </summary>
        [Input("subjectCommonName")]
        public Input<string>? SubjectCommonName { get; set; }

        public WebAccelCertificateState()
        {
        }
    }
}
