// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sakuracloud.Outputs
{

    [OutputType]
    public sealed class GetVPCRouterPublicNetworkInterfaceResult
    {
        /// <summary>
        /// A list of ip alias assigned to the VPC Router. This is only used when `plan` is not `standard`.
        /// </summary>
        public readonly ImmutableArray<string> Aliases;
        /// <summary>
        /// The list of the IP address assigned to the VPC Router. This will be only one value when `plan` is `standard`, two values otherwise.
        /// </summary>
        public readonly ImmutableArray<string> IpAddresses;
        /// <summary>
        /// The id of the switch connected from the VPCRouter.
        /// </summary>
        public readonly string SwitchId;
        /// <summary>
        /// The virtual IP address of the VPC Router. This is only used when `plan` is not `standard`.
        /// </summary>
        public readonly string Vip;
        /// <summary>
        /// The Virtual Router Identifier. This is only used when `plan` is not `standard`.
        /// </summary>
        public readonly int Vrid;

        [OutputConstructor]
        private GetVPCRouterPublicNetworkInterfaceResult(
            ImmutableArray<string> aliases,

            ImmutableArray<string> ipAddresses,

            string switchId,

            string vip,

            int vrid)
        {
            Aliases = aliases;
            IpAddresses = ipAddresses;
            SwitchId = switchId;
            Vip = vip;
            Vrid = vrid;
        }
    }
}
