// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sakuracloud.Outputs
{

    [OutputType]
    public sealed class MobileGatewayTrafficControl
    {
        /// <summary>
        /// The flag to enable the traffic shaping.
        /// </summary>
        public readonly bool? AutoTrafficShaping;
        /// <summary>
        /// The bandwidth allowed when the traffic shaping is enabled.
        /// </summary>
        public readonly int? BandWidthLimit;
        /// <summary>
        /// The flag to enable email notification when the traffic shaping is enabled.
        /// </summary>
        public readonly bool? EnableEmail;
        /// <summary>
        /// The flag to enable slack notification when the traffic shaping is enabled.
        /// </summary>
        public readonly bool? EnableSlack;
        /// <summary>
        /// The threshold of monthly traffic usage to enable to the traffic shaping.
        /// </summary>
        public readonly int Quota;
        /// <summary>
        /// The webhook URL used when sends notification. It will only used when `enable_slack` is set `true`.
        /// </summary>
        public readonly string? SlackWebhook;

        [OutputConstructor]
        private MobileGatewayTrafficControl(
            bool? autoTrafficShaping,

            int? bandWidthLimit,

            bool? enableEmail,

            bool? enableSlack,

            int quota,

            string? slackWebhook)
        {
            AutoTrafficShaping = autoTrafficShaping;
            BandWidthLimit = bandWidthLimit;
            EnableEmail = enableEmail;
            EnableSlack = enableSlack;
            Quota = quota;
            SlackWebhook = slackWebhook;
        }
    }
}
