// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Get information about an existing ESME.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sakuracloud from "@pulumi/sakuracloud";
 *
 * const foobar = pulumi.output(sakuracloud.getESME({
 *     filter: {
 *         names: ["foobar"],
 *     },
 * }, { async: true }));
 * ```
 */
export function getESME(args?: GetESMEArgs, opts?: pulumi.InvokeOptions): Promise<GetESMEResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("sakuracloud:index/getESME:getESME", {
        "filter": args.filter,
    }, opts);
}

/**
 * A collection of arguments for invoking getESME.
 */
export interface GetESMEArgs {
    /**
     * One or more values used for filtering, as defined below.
     */
    readonly filter?: inputs.GetESMEFilter;
}

/**
 * A collection of values returned by getESME.
 */
export interface GetESMEResult {
    /**
     * The description of the ESME.
     */
    readonly description: string;
    readonly filter?: outputs.GetESMEFilter;
    /**
     * The icon id attached to the ESME.
     */
    readonly iconId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the ESME.
     */
    readonly name: string;
    /**
     * The API URL for send SMS with generated OTP.
     */
    readonly sendMessageWithGeneratedOtpApiUrl: string;
    /**
     * The API URL for send SMS with inputted OTP.
     */
    readonly sendMessageWithInputtedOtpApiUrl: string;
    /**
     * Any tags assigned to the ESME.
     */
    readonly tags: string[];
}
