// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSSHKey(args?: GetSSHKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetSSHKeyResult> & GetSSHKeyResult {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    const promise: Promise<GetSSHKeyResult> = pulumi.runtime.invoke("sakuracloud:index/getSSHKey:getSSHKey", {
        "filter": args.filter,
    }, opts);

    return pulumi.utils.liftProperties(promise, opts);
}

/**
 * A collection of arguments for invoking getSSHKey.
 */
export interface GetSSHKeyArgs {
    readonly filter?: inputs.GetSSHKeyFilter;
}

/**
 * A collection of values returned by getSSHKey.
 */
export interface GetSSHKeyResult {
    readonly description: string;
    readonly filter?: outputs.GetSSHKeyFilter;
    readonly fingerprint: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly publicKey: string;
}
