// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get information about an existing sakuracloud_webaccel.
 */
export function getWebAccel(args?: GetWebAccelArgs, opts?: pulumi.InvokeOptions): Promise<GetWebAccelResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("sakuracloud:index/getWebAccel:getWebAccel", {
        "domain": args.domain,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getWebAccel.
 */
export interface GetWebAccelArgs {
    /**
     * .
     */
    domain?: string;
    /**
     * .
     */
    name?: string;
}

/**
 * A collection of values returned by getWebAccel.
 */
export interface GetWebAccelResult {
    /**
     * .
     */
    readonly cnameRecordValue: string;
    readonly domain: string;
    /**
     * .
     */
    readonly domainType: string;
    /**
     * .
     */
    readonly hasCertificate: boolean;
    /**
     * .
     */
    readonly hostHeader: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    /**
     * .
     */
    readonly origin: string;
    /**
     * .
     */
    readonly siteId: string;
    /**
     * .
     */
    readonly status: string;
    /**
     * .
     */
    readonly subdomain: string;
    /**
     * .
     */
    readonly txtRecordValue: string;
}

export function getWebAccelOutput(args?: GetWebAccelOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetWebAccelResult> {
    return pulumi.output(args).apply(a => getWebAccel(a, opts))
}

/**
 * A collection of arguments for invoking getWebAccel.
 */
export interface GetWebAccelOutputArgs {
    /**
     * .
     */
    domain?: pulumi.Input<string>;
    /**
     * .
     */
    name?: pulumi.Input<string>;
}
